greetings_file: "../etc/greetings.txt"
vocabulary_file: "../etc/vocabulary.txt"
keywords_file: "../etc/keywords.txt"
custom_dictionary_file: "../etc/custom_dictionary.txt"
word_frequency_file: "../etc/word_frequency.txt"
dict_file: "../etc/dict.txt"
idf_file: "../etc/idf.txt"
stop_words_file: "../etc/stop_words.txt"
generated_stop_words_file: "../etc/stopwords.txt"
