greetings_file: "../../cli/etc/greetings.txt"
vocabulary_file: "../../cli/etc/vocabulary.txt"
keywords_file: "../../cli/etc/keywords.txt"
custom_dictionary_file: "../../cli/etc/custom_dictionary.txt"
word_frequency_file: "../../cli/etc/word_frequency.txt"
dict_file: "../../cli/etc/dict.txt"
idf_file: "../../cli/etc/idf.txt"
stop_words_file: "../../cli/etc/stop_words.txt"
generated_stop_words_file: "../../cli/etc/stopwords.txt"
